### ISSUE TITLE
useClipboard: not quite working

### ISSUE THREAD

**Issue by mspoulsen** [Tarektouati/vue-use-web#105]
Thanks for a nice library. I have an issue with useClipboard when used in a component.

Problem: 
Does not capture copies in other tabs or applications because it is only listening to copy events in its own tab.

Suggestion:
Expose read and write functions so that the clipboard is read on each access.

```javascript
export function useClipboard() {
  async function read() {
    return await navigator.clipboard.readText()
  }

  function write(txt: string): void {
    navigator.clipboard.writeText(txt)
  }

  return {
    write,
    read
  }
}
```

**Comment by Tarektouati** [comment]
Hey @mspoulsen ! Thanks for the suggestion, would you be interested in PRing this?
