### ISSUE TITLE
Type of useFetch() in dist folder does not match implementation

### ISSUE THREAD

**Issue by GauthierPLM** [Tarektouati/vue-use-web#144]
The type of useFetch() does not match the real implementation:

type distributed with the package:

```typescript
import { Ref } from '@vue/composition-api';
export declare function useFetch(url: RequestInfo, options: RequestInit): {
    blob: Ref<Blob | null>;
    json: Ref<any>;
    text: Ref<string>;
    status: Ref<number | undefined>;
    statusText: Ref<string>;
    headers: Ref<Record<string, string>>;
    isLoading: Ref<boolean>;
    cancelled: Ref<boolean>;
    error: Ref<boolean>;
    success: Ref<boolean>;
    cancel: () => void;
    execute: () => Promise<void>;
};
```
[
Type in the implementation](https://github.com/Tarektouati/vue-use-web/blob/master/src/Fetch.ts#L76)

This cause Webstorm not to recognise the "response" element of the returned object as well as complaining about a missing argument when useFetch is only called with its first argument (`useFetch("/api/work")`).

**Comment by Tarektouati** [comment]
Hey @GauthierPLM ! Thanks for the opening an issue and your interest in this project, I'll open a PR soon to fix this issue.

**Comment by Tarektouati** [comment]
Hey @GauthierPLM ! Thanks for opening an issue and your interest in this project.
Actually, `useFetch`  API has been rewritten and does no more match that type definition but it still not released yet, I've updated the docs before the release.
For the moment `useFetch` on `v0.10.1` matches your type definition.

Let me know if you need further information.

**Comment by Tarektouati** [comment]
on `v0.10.1` here's is the API of `useFetch`: 
```vue
<template>
  <div>
    <div>{{ isLoading }}</div>
    <div>{{ success }}</div>
    <div>{{ text }}</div>
    <div>{{ blob }}</div>
    <div>{{ json }}</div>
    <div>{{ cancelled }}</div>
    <button @click="cancel">Cancel Request</button>
  </div>
</template>

<script>
import { useFetch } from 'vue-use-web';

export default {
  setup() {
    const { isLoading, error, success, cancel, text, blob, json, cancelled } = useFetch('/data.json');
    return { isLoading, error, success, cancel, text, blob, json, cancelled };
  }
};
</script>
```
