### ISSUE TITLE
Make `useFetch()` return properly-parsed output based on Content-Type response header

### ISSUE THREAD

**Issue by lbssousa** [Tarektouati/vue-use-web#40]
Instead of just returning all `res.blob()`, `res.text()`, `res.json()` alternative outputs from `useFetch()` at once, you could just return a single output, properly parsed based on the value of `Content-Type` response header:
* if it's `application/json`, return `res.json()`
* if it's another text-based MIME type, return `res.text()`
* if it's a binary MIME type, return `res.blob()`

**Comment by logaretm** [comment]
I agree, this is more useful than raw responses.
