### ISSUE TITLE
Cannot use DeviceMotion acceleration

### ISSUE THREAD

**Issue by nitnahtnit** [Tarektouati/vue-use-web#45]
Hello, I'm trying to use this to get acceleration values but when trying to use the code in the sample 
```
<template>
  <div>
    <h2>acceleration is:</h2>
    <p>x:{{ acceleration.x }}</p>
    <p>y:{{ acceleration.y }}</p>
    <p>z:{{ acceleration.z }}</p>
    <h2>rotation rate is:</h2>
    <p>alpha:{{ rotationRate.alpha }}</p>
    <p>beta:{{ rotationRate.beta }}</p>
    <p>gamma:{{ rotationRate.gamma }}</p>
  </div>
</template

<script>
import { useDeviceMotion } from "vue-use-web";

export default {
  setup() {
    const { acceleration, rotationRate } = useDeviceMotion();

    return { acceleration, rotationRate };
  }
};
</script>
```

The app breaks when trying to use {{ acceleration.x }}

On desktop console I am getting

[Vue warn]: Property or method "acceleration" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <App> at src/App.vue
       <Root>

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'x' of undefined"

found in

---> <App>
       <Root>

This is what my App.vue looks like

```
<template
  <div id="app">
    <div>
      <img alt="Vue logo" src="./assets/logo.png">
    </div>

    <div>
      <p>{{ acceleration.x }}</p>
    </div>
  </div>
</template>

<script>
import { useDeviceMotion } from "vue-use-web";

export default {
  name: 'app',

  setup(){
    const { acceleration } = useDeviceMotion();
    return { acceleration };
  }
}
</script>
```

**Comment by nitnahtnit** [comment]
I've got the acceleration object displaying by adding 

```
import CompositionApi from '@vue/composition-api'
Vue.use(CompositionApi)
```

But now the acceleration.x, acceleration.y and acceleration.z are all displayed as 'null' and not updating

**Comment by logaretm** [comment]
> On desktop

That API is not available for typical desktop devices

> I want to get acceleration data from a mobile phone browser

This features require an acceleration sensor, so you might need to enable it in browser features, make sure to check the compatibility table as well.

I will try to setup examples for each API
